//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_Bibliotheque.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SkyBiblioEntities : DbContext
    {
        public SkyBiblioEntities()
            : base("name=SkyBiblioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Livres> Livres { get; set; }
        public virtual DbSet<Membres> Membres { get; set; }
        public virtual DbSet<Prets> Prets { get; set; }
        public virtual DbSet<Reservation> Reservation { get; set; }
    }
}
