//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_Bibliotheque.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int Id_Reserv { get; set; }
        public int Id_Livres { get; set; }
        public int Id_Membres { get; set; }
    
        public virtual Livres Livres { get; set; }
        public virtual Membres Membres { get; set; }
    }
}
